### ISSUE TITLE
soft reset button creates new window 

### ISSUE THREAD

**Issue by alpharesearch** [nsiatras/sourcerabbit-gcode-sender#1]
Sometimes pressing the soft reset button creates new window, but both windows are usable?

**Comment by nsiatras** [comment]
Hello,

Are you sure is this happening?
There is no method in the code that re-opens the window.

**Comment by nsiatras** [comment]
If you are running the GCode Sender from code:

Inside frmMain there is a method OpenControlForm.
This method closed frmMain and opens frmControl and removes the fConnectionEstablishedEventListener.

Just check if this is happening

**Comment by alpharesearch** [comment]
Here is a private video of the issue: http://youtu.be/nSEtekoV6t4
I do run it from Netbeans 8.0.2, but it only happens when if fails to connect first... I guess something is not cleaned up properly... I only added this line:
jComboBoxPort.addItem("/tmp/ttyV1");
so I don't have to type my com port in all the time...

**Comment by nsiatras** [comment]
Hello,

Thank you for the video. It was very helpful!
I just fixed the bug and pushed it to GitHub.

Thank you !

**Comment by alpharesearch** [comment]
works good now

**Comment by nsiatras** [comment]
You are welcome!
