### ISSUE TITLE
Slow tool entry when using inches

### ISSUE THREAD

**Issue by memsengineer** [nsiatras/sourcerabbit-gcode-sender#10]
I am using fusion 360 on windows 7 driving a Shapeoko 3 CNC router. I am using sourcerabbit 1.2.0

When I use inches in fusion 360, the tool moves as expected above the stock to the entry point. Then the tool begins to spiral into the stock very very slowwwly. 

I experimented a bit and switched fusion 360 to millimeters. Now it seems to work correctly. The tool entry spiral is the expected speed.

Am I doing something else wrong with fusion 360 or is it really a source rabbit issue? I googled pretty hard but could find no one else reporting this.

**Comment by nsiatras** [comment]
Hello,

I believe that issue has to do with the post processor you are using.
The SourceRabbit GCode sender just sends the GCode to the controller.
