### ISSUE TITLE
Add support for M6 Tool change

### ISSUE THREAD

**Issue by skendrot** [nsiatras/sourcerabbit-gcode-sender#13]
Adding support for the M6 Tool change command would allow for sending one file to run rather than opening multiple files for a single project.

**Comment by nsiatras** [comment]
Hello,

We just published version 1.2.4 which handles the M6 (Tool Change) command
You can see a video of the tool change function on YouTube
https://www.youtube.com/watch?v=ueCJ0o1xFS8
