### ISSUE TITLE
Vectric Postprocessor for sourcerabbit-gcode-sender

### ISSUE THREAD

**Issue by luisluna2** [nsiatras/sourcerabbit-gcode-sender#7]
Hello guys, I have a problem in the postprocesor in Aspire Vectric, in th screen not show nothing and when send the code only move in a line ad stop.

With Vectric:
![image](https://user-images.githubusercontent.com/38824145/39969653-a4e0d24a-56a4-11e8-836c-eaab39f6e5a7.png)

With ESTLCAM
![image](https://user-images.githubusercontent.com/38824145/39969655-b58e44c4-56a4-11e8-99cd-8e9f47f0ba14.png)

With ESTLCAM all is good but someody knows in which site is the Marlin postprocessor in ESTLCAM?

**Comment by nsiatras** [comment]
Sorry for the late reply..
It is a post processor compatibility problem. The post processor you are using with the Vectric software seems to be incompatible with GRBL
