### ISSUE TITLE
Hole Center Finder not working

### ISSUE THREAD

**Issue by haaxema** [nsiatras/sourcerabbit-gcode-sender#8]
Hi,

I am having a problem with the "Hole Center Finder" and I think I found the problem in the Code:

In Process_HoleCenterFinder.java there is a variable called "fMaxDistance = 50000;"
50000 equels 50 meters? thats a large hole to probe.

If I enable Softlimits in GRBL the "Hole Center Finder" just does not work (soft limits),
if I disable Softlimits the steppers get enabled (tock) but my best gues is that GRBL craches on a 50 meter probe.

I wil look in to the GRBL code, but it would be "nice" if SourceRabbit changes the probe distance to something more realistic.

Martin

**Comment by nsiatras** [comment]
You will be able to set that distance with our later version :) Give it a try
